inoremap <C-d> <C-x><C-k>
inoremap <C-l> <C-x><C-l>
""inoremap <C-o> <C-x><C-o>
inoremap <C-t> <C-x><C-t>
inoremap <C-f> <C-x><C-f>
inoremap <C-u> <C-x><C-u>
inoremap <C-v> <C-x><C-v>
inoremap <leader>gn <Esc>nviw
inoremap <leader>gN <Esc>NNviw
inoremap <leader>gp <Esc>NNviw
